### ISSUE TITLE
ECSTaskSensor returns a value and thus is saved to xcom

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/workflow#14]
```
if a task returns a value (either from its Operator’s execute() method, or from a
PythonOperator’s python_callable function), then an XCom containing that value
is automatically pushed.
```
https://airflow.apache.org/concepts.html?highlight=xcom#xcoms

You can see this here:
https://airflow-stage.mitlib.net/xcom/list/

We should determine if there is a default expire / purge of xcom. If not, we should create cleanup tasks.

**Comment by gravesm** [comment]
I think you mean the ecs operator is pushing onto xcom. The sensor returns True/False from the `poke()` method because this is how it determines whether the sensor is activated or not. The operator returning a value is intentional because the sensor is using xcom to get the ecs task arn.

The question of whether/how to clear out xcom is probably a larger question of whether we should clear out old dag runs. Since the xcom is tied to a task instance, I would guess clearing the task instance would also clear the xcom. If we want to clear anything, that's probably where we should be clearing it.

**Comment by JPrevost** [comment]
Works for me. I'll close this ticket.
